### ISSUE TITLE
Refactor Contact Us Page with Bootstrap

### ISSUE THREAD

**Issue by bhrayhaw** [bhrayhaw/musicplug#27]

**Comment by AngelKafui4** [comment]
- [x] Contact form component fields
    - Name
    - Email 
    - Message 
- [x] Live alert button displaying a message to confirm form submission. 
- [x] Dismiss button to close the contact form
- [x] Utilize Bootstrap's grid system
- [x] Reference the wireframe to ensure your grid and content layers are correct
